### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by JoshuaAndrew** [mhausenblas/cinf#1] opened 2016-10-25 09:21 UTC
root@client0:~# cinf 
Segmentation fault

**Comment by mhausenblas** [comment] 2016-10-25 09:37
@JoshuaAndrew thanks for raising this issue, can you be a bit more specific concerning your environment pls? What system, for starters (`uname -a`)?

**Comment by JoshuaAndrew** [comment] 2016-10-25 09:43
@mhausenblas 
root@client0:~# cinf 
Segmentation fault
root@client0:~# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
root@client0:~# docker --version
Docker version 1.12.2, build bb80604

**Comment by mhausenblas** [comment] 2016-10-25 09:45
@JoshuaAndrew thanks. Quick question: does it also happen if you're not root but execute it with `sudo`?

**Comment by JoshuaAndrew** [comment] 2016-10-25 09:49
@mhausenblas 
joshua@client0:~$ sudo DEBUG=true cinf
joshua@client0:~$ sudo cinf
joshua@client0:~$ sudo cinf
joshua@client0:~$ 
joshua@client0:~$ 
joshua@client0:~$

no output!

**Comment by mhausenblas** [comment] 2016-10-25 09:52
Strange. Just tried to reproduce it but works fine for me 8->

What version are you on, that is, what version does `cinf --version` report?

**Comment by JoshuaAndrew** [comment] 2016-10-25 09:56
joshua@client0:~$ sudo cinf --version
joshua@client0:~$ 
joshua@client0:~$ sudo cinf --version
joshua@client0:~$ 

no output too!   well  I installed v0.4.0-alpha

**Comment by mhausenblas** [comment] 2016-10-25 10:00
OK, that really is strange, one would expect that it can at least output its version. Two more things to check (running slowly out of ideas what the cause could be here): can you execute `cinf` alone (that is, without `sudo`) and what is the output there. Also, maybe related, what does `sudo apparmor_status` give?

**Comment by mhausenblas** [comment] 2016-10-25 18:36
Are you still having this problem @JoshuaAndrew? Otherwise I'm closing this for now …

**Comment by JoshuaAndrew** [comment] 2016-10-26 01:57
@mhausenblas 

joshua@client0:~$ cinf
Segmentation fault
joshua@client0:~$ sudo apparmor_status 
apparmor module is loaded.
21 profiles are loaded.
21 profiles are in enforce mode.
   /sbin/dhclient
   /usr/bin/evince
   /usr/bin/evince-previewer
   /usr/bin/evince-previewer//sanitized_helper
   /usr/bin/evince-thumbnailer
   /usr/bin/evince-thumbnailer//sanitized_helper
   /usr/bin/evince//sanitized_helper
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/connman/scripts/dhclient-script
   /usr/lib/cups/backend/cups-pdf
   /usr/lib/lightdm/lightdm-guest-session
   /usr/lib/lightdm/lightdm-guest-session//chromium
   /usr/lib/telepathy/mission-control-5
   /usr/lib/telepathy/telepathy-*
   /usr/lib/telepathy/telepathy-*//pxgsettings
   /usr/lib/telepathy/telepathy-*//sanitized_helper
   /usr/lib/telepathy/telepathy-ofono
   /usr/sbin/cups-browsed
   /usr/sbin/cupsd
   /usr/sbin/tcpdump
   docker-default
0 profiles are in complain mode.
12 processes have profiles defined.
12 processes are in enforce mode.
   /usr/sbin/cups-browsed (1064) 
   /usr/sbin/cupsd (4134) 
   docker-default (23250) 
   docker-default (23273) 
   docker-default (23283) 
   docker-default (23284) 
   docker-default (23286) 
   docker-default (23287) 
   docker-default (23288) 
   docker-default (23289) 
   docker-default (23290) 
   docker-default (23291) 
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.

suggest you look at this article: https://en.wikipedia.org/wiki/Segmentation_fault
I guess it's a fault of the program itself.

**Comment by mhausenblas** [comment] 2016-10-26 05:21
@JoshuaAndrew we still haven't found the cause (and thanks, yeah, I know what a seg fault is but that doesn't help me since I have nothing to go on). The fact that apparently it does produce zero output when you call it without sudo and as a non-root user, even for the simple case of printing it's own version is very odd. Since I can't reproduce the issue, only thing I can suggest is that you try it out on a different system.

**Comment by mhausenblas** [comment] 2016-10-26 07:27
OK, one more thing we could try @JoshuaAndrew … can you do `strace cinf` or `sudo strace cinf` whatever gives an actual output and no seg fault?

**Comment by JoshuaAndrew** [comment] 2016-10-26 10:00
joshua@client0:~$ sudo strace cinf
execve("/usr/local/bin/cinf", ["cinf"], [/* 24 vars */]) = -1 EFAULT (Bad address)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_USER, si_pid=1282, si_uid=0} ---
+++ killed by SIGSEGV +++
joshua@client0:~$ 
joshua@client0:~$ 
joshua@client0:~$ 
joshua@client0:~$ 
joshua@client0:~$ strace cinf
execve("/usr/local/bin/cinf", ["cinf"], [/* 30 vars */]) = -1 EFAULT (Bad address)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_USER, si_pid=1316, si_uid=1000} ---
+++ killed by SIGSEGV +++
Segmentation fault (core dumped)

**Comment by mhausenblas** [comment] 2016-10-26 10:21
@JoshuaAndrew thanks! Just to make sure I understand, you did install the binary via `curl -s -L https://github.com/mhausenblas/cinf/releases/download/v0.4.0-alpha/cinf -o cinf`, right?

**Comment by mhausenblas** [comment] 2016-10-27 05:07
@JoshuaAndrew can you let me know if you used the binary I provided or built it yourself? Otherwise I consider this a wontfix …

**Comment by mhausenblas** [comment] 2016-10-27 18:20
OK, closing for now since I can't reproduce it and don't have further info as to what the root cause might be. We can re-open it if some new infos come up.

**Closed by mhausenblas** 2016-10-27 18:20 UTC
Labels: bug
